### ISSUE TITLE
Hammerhead crashes if script file contains a sourcemap comment

### ISSUE THREAD

**Issue by LavrovArtem** [DevExpress/testcafe-hammerhead#1052]
Maybe we need to remove the source map comment from the script.

**Comment by miherlosev** [comment]
Steps to reproduce:
1)Open https://microsoft.github.io/monaco-editor/playground.html in a playground
2)Open ChromeDeveloperTools

Then you are getting the following errors in a console:
```js
(node:10280) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Protocol "http:" not supported. Expected "https:"
(node:10280) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Protocol "http:" not supported. Expected "https:"
(node:10280) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: Protocol "http:" not supported. Expected "https:"
(node:10280) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: Protocol "http:" not supported. Expected "https:"
```

It happens because:
- Monaco Editor scripts contain sourceMap directives. 
For example, the script http://localhost:8080/node_modules/monaco-editor/dev/vs/loader.js contains
```js
//# sourceMappingURL=loader.js.map
```
- on open DeveloperTools browser send request for sourceMap to a proxy. It sends as script.
```/Bkh0nzQWb!s!utf-8/http:/localhost:8080/node_modules/monaco-editor/min-maps/vs/loader.js.map```
-after it proxy failed

We will remove sourceMap definition from script files

**Comment by miherlosev** [comment]
I'm working on this

**Comment by miherlosev** [comment]
https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit

**Comment by doronsever** [comment]
Any news about this one? I'm trying to test it with my Angular TS localhost and getting errors because of it

**Comment by doronsever** [comment]
Now after I rerun I'm not sure it is related, but when i'm running my Angular(6) app via localhost I'm getting this error: `Error [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:"
`

**Comment by doronsever** [comment]
Should I open a new issue for it?

**Comment by miherlosev** [comment]
Yes, it's a separate issue. Please open a new issue and share a simple example to reproduce.
