### ISSUE TITLE
Allow adjustable timeouts for requests

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe-hammerhead#1072]
Currently we have a constant 25 secs timeout for regular proxied request, and a 2 mins timeout for proxied XHRs. It's not enough sometimes, so we should allow users to configure these timeouts.

**Comment by miherlosev** [comment]
Initial problem: 
After site was updated on the IIS server it has a long time for first request. 
It happens because site is cold(little modules load into memory).

We discussed about this and decide that it should be fixed with [warm up site](https://docs.microsoft.com/en-us/iis/get-started/whats-new-in-iis-8/iis-80-application-initialization).

If there is an another real life example then we will reopen this issue.
