### ISSUE TITLE
Site http://www.about.com/ hung under playground

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#1154]
see [video](https://www.screencast.com/t/R6fs82bgij0)

**Comment by miherlosev** [comment]
http://soso.com too

**Comment by LavrovArtem** [comment]
@miherlosev  No, http://soso.com is just unavailable sometimes.

**Comment by LavrovArtem** [comment]
Site http://www.about.com/ hung under playground because it is answered with the invalid responce.
https://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html
```
Response      = Status-Line
                *(( general-header
                 | response-header
                 | entity-header ) CRLF)
                CRLF                      // <— this required line is missed
                [ message-body ]
```
Server for reproducing:
```javascript
require('net').createServer(c => {
    c.write('HTTP/1.1 301 Moved Permanently\r\n' +
            'Location: https://www.dotdash.com/\r\n');
    c.end();
}).listen(1234);
```
The calling `http.request()` to `localhost:1234` throws an error with text `socket hang up`. But if we add `+ '\r\n'` to the responce, everything will work correctly.
Chrome, Firefox end IE correctly parse this invalid responce.

@miherlosev @churkin @AlexanderMoskovkin Do we need to fix it?

**Comment by miherlosev** [comment]
I think we should not fix this issue on our side until issue appears several times.
It looks like a boundary case.

**Comment by LavrovArtem** [comment]
ping @churkin @AlexanderMoskovkin what do you think?

**Comment by AlexanderMoskovkin** [comment]
I suppose we can leave it as is for now. It'll be a signal to fix the response for a site owner. Let's return to it once someone faces with it

**Comment by LavrovArtem** [comment]
Also http://thehill.com/
