### ISSUE TITLE
Abnormally loading time on page https://globalchallenges.org

### ISSUE THREAD

**Issue by helen-dikareva** [DevExpress/testcafe-hammerhead#1177]
url: https://globalchallenges.org/en/submission-platform/register

**Comment by miherlosev** [comment]
Measurements on the my computer (browser - Google Chrome: Version 59.0.3071.86 (Official Build) (64-bit))
without proxy: 
- first load: `DOMContentLoaded` - 2.2 sec, `Load`: 5 sec
- second and later: `DOMContentLoaded` - 1.9 sec, `Load`: 4.3 sec

with proxy:
- first load: `DOMContentLoaded` - 22 sec, `Load`: 32 sec
- second and later: `DOMContentLoaded` - 5.5 sec, `Load`: 11.3 sec

There are several issues for this site:
- long initialization for brotli module (see issue https://github.com/devongovett/brotli.js/issues/14)
![long-brotli-initialization](https://user-images.githubusercontent.com/4133518/27141838-f0cbedd0-5131-11e7-8a40-2a80fc8bf3a2.png)

- a lot of count `__get$`  calls for wrapped properties (especially for https://globalchallenges.org/main.66eea6068567b30ef55a.bundle.js)
![bottom-up-call-tree](https://user-images.githubusercontent.com/4133518/27141520-1848b1d2-5131-11e7-841d-a37eecdd06dc.png)

**Comment by LavrovArtem** [comment]
issue related with brotli fixed in https://github.com/DevExpress/testcafe-hammerhead/pull/1310

**Comment by LavrovArtem** [comment]
Currently on the my computer (browser - Google Chrome: Version 60.0.3112.113 (Official Build) (64-bit))
without proxy:

* first load: DOMContentLoaded - 1.92s, Load: 2.93s
* second and later: DOMContentLoaded - 532ms, Load: 1.48s

with proxy:

* first load: DOMContentLoaded - 3.99s, Load: 6.61s
* second and later: DOMContentLoaded - 1.05s, Load: 2.42s

**Comment by LavrovArtem** [comment]
We have to revert the fix since we've faced a major issue there. The [iltorb](https://www.npmjs.com/package/iltorb) module requires the c++ compiler. There are compiled binaries for linux, win and mac platforms for nodejs versions 4, 6 and 8. But if you use it with nodejs v5 or v7 node tries to compile c++ files. C++ compiler is not available on most operating systems by default. In this case the iltorb module installation fails.
We will try to find the best way to resolve this and fix the initial issue.

**Comment by miherlosev** [comment]
This issue affects 3 points: brotli encoding/decoding,  client code overriding and http caching.
We will get the greatest gain from [http caching](https://github.com/DevExpress/testcafe-hammerhead/issues/863)
