### ISSUE TITLE
Wrong `history` navigation in Chrome

### ISSUE THREAD

**Issue by helen-dikareva** [DevExpress/testcafe-hammerhead#1184]
Test works in Firefox and fails in Chrome:
```js
import { ClientFunction } from 'testcafe';

fixture `Test fixture`
    .page `http://example.com/`;

const getLocation = ClientFunction(() => document.location.href);

test('test', async t => {
    await t
        .navigateTo('http://google.com')
        .expect(getLocation()).contains('google')
        .navigateTo('https://habrahabr.ru/top/')
        .expect(getLocation()).contains('habrahabr')
        .navigateTo('javascript:history.go(-1)')

        // NOTE: in Chrome location is http://example.com/
        .expect(getLocation()).contains('google');
});
```

**Comment by miherlosev** [comment]
I'm working on this

**Comment by miherlosev** [comment]
Two points:
1. I think we should prevent using javascript protocol in the `navigateTo` action.

Because:
- we already have 2 ways to execute a client code: `eval` and `ClientFunction`. 
- it can cause indeterminate behavior in a future. 
 `navigateTo('javascript:expression')` transforms to `window.location = 'javascript:expression';`
  `window.location` is shortcut of the `window.location.href`. 
  So, `window.location = javascript:expression'` is equivalent of the `window.location.href = javascript:expression'`;
  In specification there is no information about using javascript protocol for the `href` setter.
  https://html.spec.whatwg.org/multipage/history.html#dom-location-href
/cc  @AlexanderMoskovkin 

2.  With proxing site https://habrahabr.ru/top/ doesn't put into window.history.
It looks like a bug and I will investigate this.

**Comment by miherlosev** [comment]
Problem: after `navigateTo` action the `history.length` doesn't changed.
```js
import { ClientFunction } from 'testcafe';

fixture `Test fixture`
    .page `http://example.com/`;

const getHistoryLength = ClientFunction(() => window.history.length);

test('test', async t => {
	const urls = [
		'https://habrahabr.ru/top/',
		'http://google.com',
		'https://mail.ru',
		'https://news2.ru'
	];

    console.log(await getHistoryLength()); //2
  
    for (let url of urls) {
	await t.navigateTo('https://habrahabr.ru/top/');
        console.log(await getHistoryLength()); // chrome and ie - 3
   }
});
```

**Comment by LavrovArtem** [comment]
Do you mean
```javascript
for (let url of urls) {
    await t.navigateTo(url);
```
instead of
```javascript
for (let url of urls) {
    await t.navigateTo('https://habrahabr.ru/top/');
```
??

**Comment by miherlosev** [comment]
Yes. I've updated the code example.
