### ISSUE TITLE
Logging doesn't work on https://www.soudfa.com/signup

### ISSUE THREAD

**Issue by helen-dikareva** [DevExpress/testcafe-hammerhead#1385]
Based on [question](https://testcafe-discuss.devexpress.com/t/logging-into-facebook-using-roles/613/2)
It can be reproduced via hammerhead-playground by execution following steps
```js
await t
            .click('button.facebook')
            .typeText('#email', 'email, { replace: true })
            .typeText('#pass', 'password', { replace: true })
            .click('#loginbutton') //nothing happends after it
```

**Comment by MohamedRasool786** [comment]
@LavrovArtem 

I have faced issue while clicking on a #googleSignInn button. It doesn't redirect to the google POPUP page.Below I attached my code

Expected Behaviour is to give my credentials in google popup page and then it should redirect to my homesite.

Thanks in advance

`import { ClientFunction, Role, Selector } from 'testcafe';

const patchAuth = ClientFunction(() => {
    window['op' + 'en'] = function (url) {
        var iframe = document.createElement('iframe');

        iframe.style.position = 'fixed';
        iframe.style.left = '100px';
        iframe.style.top = '150px';
        iframe.style.width = '600px';
        iframe.style.height = '600px';
        iframe.style['z-index'] = '99999999';;		
        iframe.src = url;
        iframe.id = 'auth-iframe';

        document.body.appendChild(iframe);
    };
});

const googleAccUser = Role('https://merida-web.herokuapp.com/', async t => {
    await patchAuth();

    await t
        .click("#LoggIn")
        .click("#googleSignInn")  
        .switchToIframe('#auth-iframe')
        .typeText('#identifierId', 'mohamed@cogzidel.com')
         .click("#identifierNext")
         .typeText('#password', 'maduraiboys007')
         .click("#passwordNext")
        .switchToMainWindow();

    await Selector('#page-header-top-menu')();
});

fixture `Merida E2E Testing`
    .page `https://merida-web.herokuapp.com/`
    .beforeEach(async t => await t.useRole(googleAccUser));
	
test('first test', async t => {
    await t.click(Selector('.dashboard-tab').nth(2));
});`

**Comment by LavrovArtem** [comment]
@MohamedRasool786 
https://github.com/DevExpress/testcafe-hammerhead/issues/1428#issuecomment-399098871
