### ISSUE TITLE
Cookie synchronization with server is too slow

### ISSUE THREAD

**Issue by LavrovArtem** [DevExpress/testcafe-hammerhead#1486]
The xhr request may outrun the cookie synchronization and send request to destination server without cookie. But it can be if client script sets a cookie right before it will send a request.

**Comment by tk8817** [comment]
Hey @LavrovArtem and @miherlosev - our team opened the original issue which spawned this https://github.com/DevExpress/testcafe/issues/2106 and we were wondering if there is any update you can share? 

We were quite excited with how fast you were able to reproduce and track down the issue, but it seems very quite since then. Let us know if there is anything we can do to help.

**Comment by miherlosev** [comment]
@tk8817 
We have plans to start working on the problem next week.

**Comment by tatthipatla** [comment]
Is this issue fixed? We do have issues with invalid xsrf token.
