### ISSUE TITLE
WebSocket connect to a wrong URL

### ISSUE THREAD

**Issue by allayli** [DevExpress/testcafe-hammerhead#1757]
Hi,

I am using TestCafe Studio for trial, and I found that the connection for websocket cannot be established. And I got this error message:

> hammerhead.js:7 WebSocket connection to 'ws://172.20.6.148:50164/z6vKtJtz1!w!http%3A%2F%2F127.0.0.1%3A5264/http://172.20.6.149:5235' failed: Connection closed before receiving a handshake response

My HTML page is on http://127.0.0.1:5264/index.html
And TestCafe runs on http://172.20.6.148:50164/z6vKtJtz1/http://127.0.0.1:5264/index.html

My page suppose to connect to ws://172.20.6.149:5235
But when hammerhead.js calls getProxyUrl('ws://172.20.6.149:5235', {resourceType: "w"}),
it returns 'ws://172.20.6.148:50164/z6vKtJtz1!w!http%3A%2F%2F127.0.0.1%3A5264/http://172.20.6.149:5235' ,
which is a wrong URL so that no connection can be established.

I have no idea about how the proxy work, and I cannot find a way to disable the proxy.

Please help. Thanks.

**Comment by MarinaRukavitsyna** [comment]
Hello @allayli,
By design, TestCafe uses [URL-rewriting proxy](https://github.com/DevExpress/testcafe-hammerhead). With the proxy we inject scripts that emulate user actions via DOM API. So, your links are run as expected.

You can learn more about how TestCafe works internally in [this](https://testcafe-discuss.devexpress.com/t/why-not-use-selenium-how-to-use-testcafe/47/11) thread.

Please make sure that the connection is established on your page without TestCafe and there is no issue with your site.

In addition, let me know if you are using any proxy settings. If so, it is required to set up [TestCafe proxy settings](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#--proxy-host) manually. We are going to add this capability to TestCafe Studio in the official version. For now, I can only suggest you run tests using [Command Line Interface](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html).

**Comment by allayli** [comment]
Thanks @MarinaRukavitsyna .

> When hammerhead.js calls getProxyUrl('ws://172.20.6.149:5235', {resourceType: "w"}),
it returns 'ws://172.20.6.148:50164/z6vKtJtz1!w!http%3A%2F%2F127.0.0.1%3A5264/http://172.20.6.149:5235'
Is it expected? 
I suppose that even though TestCafe hijack the window.WebSocket, there should be a real websocket connection to the actual destination (saying that 'ws://172.20.6.149:5235'), or to a proxy websocket server (saying that 'ws://172.20.6.148:50164') which proxy to 'ws://172.20.6.149:5235'.

It sounds great that there is a config settings to control the proxy in the official version of TestCafe Studio.
Looking forward to the official version!

**Comment by MarinaRukavitsyna** [comment]
>Is it expected?

Yes. This is how the proxy works.
