### ISSUE TITLE
Test cases hanging due to odd html tag within UI.

### ISSUE THREAD

**Issue by christianpenrod7984** [DevExpress/testcafe-hammerhead#1888]
![issue](https://user-images.githubusercontent.com/33991831/50846539-66caa480-133d-11e9-865f-d6c33087cf34.PNG)

**Comment by christianpenrod7984** [comment]
@miherlosev The best insight I can provide regarding this issue is that before my tests execute, my browser (chrome) hangs on this screen for quite some time.  This only happens at random meaning I won't always see this issue.  A few results may happen when this occurs:
- Simple refresh may start the test back up.
- Have to wait 30+ seconds.
- The test just terminates with no failure or success status.

P.S. I've tested to see if this was a browser specific issue within Chrome; however, it seems to reproduce the same issue in firefox, edge, and ie.

**Comment by Farfurix** [comment]
@christianpenrod7984,
Thank you for the additional information. However, this information is not sufficient to find the cause of the issue. There can be many causes, and therefore we cannot give you advice without analyzing your page or code. Would you please give me a link to your site if it is public?

**Comment by christianpenrod7984** [comment]
Unfortunately I cannot give out the url.  In general, what is the typical cause(s) for such an issue?  Or at least, what is this screen indicating?

**Comment by Farfurix** [comment]
@christianpenrod7984,
This screen in your browser window may be caused by a wrong [MIME type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types). I can't, however, tell more due to the lack of information. 
Since providing an URL is not an option, please generate a [HAR report](https://community.box.com/t5/Managing-Content-Troubleshooting/How-to-Generate-a-HAR-File-in-Chrome-IE-Firefox-and-Safari/ta-p/366) for the problematic test session. This information may give us clues on why the problem occurs.
