### ISSUE TITLE
Evaluating Content-Security-Policy

### ISSUE THREAD

**Issue by vmignot** [DevExpress/testcafe-hammerhead#2032]
Hi,

I'm using testcafe as a way to evaluate non-regression on my web-front.

I've changed the `content-security-policy` and introduced a regression (I was not able to connect anymore, directive `connect-src`), but it was not detected by testcafe (running firefox and chrome, both headless, on Centos7 container).

Is there a reason why this header seams to be ignored?

Thanks!

**Comment by LavrovArtem** [comment]
Hammerhead is a URL-rewriting proxy. Therefore, we need to manually process the `content-security-policy` header on the server side instead of a browser. Currently, we have not implemented this feature and don't have any workaround for it. We will discuss it and consider implementing it in one of our future product updates.

**Comment by vmignot** [comment]
Ok, thanks for the info!
Have a good day.

**Comment by miherlosev** [comment]
Hi @vmignot 

I am collecting the all issues related to 'Content Security Policy' into the single issue . Track the #244 thread  to be notified of our progress.
