### ISSUE TITLE
'message' event handler running in an iframe is not receiving the data sent by the `postMessage` call

### ISSUE THREAD

**Issue by christianacca** [DevExpress/testcafe-hammerhead#2053]
### What is your Scenario?
The SUT is using `postMessage` from within a custom polymer web component to send data to a hidden iframe. 
 
### What is the Current behavior?

The message object that is received by the 'message' event handler has it's `data` field set to `undefined` (as is it's `origin` field)
 
### What is the Expected behavior?

The 'message' event handler running within the iframe should receive a message object with it's data field set to the object that was supplied by the `postMessage` call
 
<details>
<summary>Your complete app code (or attach your test files):</summary>

 
```js

// polymer web component running in the parent top level window:
const configs = { configuration: 'some_important_value' };
this.$.auth.contentWindow.postMessage(configs, '*');

// (okta-auth.js) event handler for the posted message running in the iframe
window.addEventListener('message', function(e) {
  // this line fails as `data` field is undefined
  if(e.data.configuration) {
    // do stuff with the e.data.configuration
  }
});

// test file
import { Selector } from 'testcafe';

fixture`Test Welcome page`
  .page`http://localhost:53660`;


test('When I navigate to the welcome page do I see the Application Gateway bar?', async t => {
  await t
    .wait(10000)
    .typeText('#ClientID', 'P123456')
    .click('#GoButton')
    .typeText('#okta-signin-username', 'blah.blah@blah.com')
    .typeText('#okta-signin-password', 'xxxxxxxx')
    .click('#okta-signin-submit')
    .wait(15000)
    .expect(Selector('application-gateway-app').exists).ok();
});

```
</details>

<details>
<summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/886590/59698098-e7dc7080-91e6-11e9-9b3e-950d75c54752.png)

</details>

 
### Your Environment details:

* node.js version:                    v10.15.3
* browser name and version: Chrome 75
* platform and version:          Windows 10 1803

**Comment by helen-dikareva** [comment]
I see the problem on your screenshot, but the code you provided is insufficient for us to reproduce the issue locally. Could you please give us access to your website? We need it to research the issue in detail. If you cannot share it here, send the account information at support@devexpress.com

**Comment by markaconrad** [comment]
@christianacca Did you by chance resolve this? We are running into the same issue.

**Comment by alexey-lin** [comment]
Hi @markaconrad,
If you reproduced the issue, please provide us with a sample project or give us access to your website so we can investigate this behavior. Thank you in advance.

**Comment by markaconrad** [comment]
> Hi @markaconrad,
> If you reproduced the issue, please provide us with a sample project or give us access to your website so we can investigate this behavior. Thank you in advance.

It appears to be related to using es6 modules a script type="module". Once they are all bundled, it works fine so we are now doing all our testing once it is bundled

**Comment by AndreyBelym** [comment]
@markaconrad yes, TestCafe can't work with your web app if it uses ES6 modules in the browser context: https://github.com/DevExpress/testcafe-hammerhead/issues/1725. We plan to support them as soon as possible.

**Comment by amal-architrave** [comment]
I have bumped in-to possibly the same issue.

###What is your Scenario?
I am dispatching a MessageEvent as a ClientFunction in my test in-order to populate data in my application. Below is the event which is working fine if I run it manually from the chrome console and a proper data is received by the application.

` window.dispatchEvent(
    new MessageEvent("message", {
      data: {
        type: "filesFromParent",
        files: [
          {
            blob: new Blob(["name"]),
            name: "name.pdf",
          },
        ],
        assetId: 1,
      }
    })
  );`

### What is the Current behavior?
When the event is dispatched as a Client Function from TestCafe "TypeError: Cannot read property 'type' of undefined" error is seen as shown in the screenshot.
![image](https://user-images.githubusercontent.com/60701371/79877380-7368f400-83ec-11ea-98b5-e7e4203a0a75.png)

When I log the event, i could see that the data object is not receiving the data send by the MessageEvent.
![image](https://user-images.githubusercontent.com/60701371/79877661-ccd12300-83ec-11ea-8323-db1fe5bcbf8f.png)


### What is the Expected behavior?

When the event is dispatched from the chrome console, everything works fine and the data object is returned with the right data as shown below.

![image](https://user-images.githubusercontent.com/60701371/79877031-09504f00-83ec-11ea-9af5-9598acc8f5d3.png)


This is the part of the application code which is listening for the event.
<details>
<summary>Your complete app code (or attach your test files):</summary>

 
```const handleEvent = async (event: MessageEvent) => {
    console.log(event);
    if (event.data.type === 'filesFromParent') {
      const { assetId, files: receivedFiles } = event.data;
      const { data } = await apiClient.getAsset(assetId);

      dispatch(
        addFiles(
          {
            ...data,
            iconUrl: `${event.origin}${data.iconFile}`,
          },
          receivedFiles.map((file: { blob: Blob; name: string }) => ({
            blob: file.blob,
            name: file.name,
            progress: 0,
            status: FileStatus.waiting,
            tempId: uuid(),
          })),
        ),
      );
    }
  };
 
```
</details>

<details>
<summary>Screenshots:</summary>

This is the starting point of my test, and only if this works I will be able proceed with automating my application. 
Any help is greatly appreciated.

**Comment by amal-architrave** [comment]
For the above mentioned issue this alternate way worked.

`var event;
  event = document.createEvent("Event");
  event.initEvent("message", false, false);
  event.data = {
    type: "filesFromParent",
    files: [
      {
        blob: new Blob(["name"]),
        name: "name.pdf",
      },
    ],
    assetId: 1,
  };
  event.origin = "hostname";
  window.dispatchEvent(event);
});`

**Comment by miherlosev** [comment]
https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events

**Comment by amal-architrave** [comment]
Thanks @miherlosev It now working with sequence which you mentioned.
