### ISSUE TITLE
Script cache key memory consumption

### ISSUE THREAD

**Issue by andrzej-kodify** [DevExpress/testcafe-hammerhead#2138]
https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/processing/resources/script.ts#L30

```
    processResource (script: string, _ctx, _charset, urlReplacer: Function) {
        if (!script)
            return script;

        let processedScript = this.jsCache.get(script);

        if (!processedScript) {
            processedScript = processScript(script, true, false, urlReplacer);
            this.jsCache.set(script, processedScript);
        }

        return processedScript;
    }
```

Does this mean that entire script is used as key in lru-cache map?
Cache size has defined max as roughly 50MB but I would assume that key length may not be considered so doesn't this double memory consumption?
How about using sha1/md5 of script as a key?

**Comment by alexey-lin** [comment]
Hi @andrzej-kodify,
 
Yes, the entire script is used as a key, and roughly 50 MB doesn't include the key size. So, the actual memory consumption can be more than 50 MB, but probably not twice as much because the original script is likely smaller than the processed one.
 
As for using a hash as a key, I suppose that resolving the hash collision might be rather tricky in this case, but if you manage to solve this problem, your PR is appreciated.
