### ISSUE TITLE
ResponseMock and RequestFilterRule classes don't have type definitions

### ISSUE THREAD

**Issue by rbardini** [DevExpress/testcafe-hammerhead#2256]
`ResponseMock` and `RequestFilterRule` classes (including a few others) don't have type definitions, even though they are exported.

**Comment by LavrovArtem** [comment]
Hello @rbardini,

The `ResponseMock` class has [exported definitions](https://github.com/DevExpress/testcafe/blob/master/ts-defs-src/test-api/request-hook.d.ts#L149). 

![image](https://user-images.githubusercontent.com/5373460/75462478-60f6af00-5995-11ea-86e1-2ee16086a54f.png)

For the `RequestFilterRule` class, I think that definitions is unnecessasery, because it is just an [Array of any](https://github.com/DevExpress/testcafe/blob/master/ts-defs-src/test-api/request-hook.d.ts#L25).

Feel free to reopen this issue if you have other questions about type definitions.

**Comment by rbardini** [comment]
Hi @LavrovArtem,

The problem is this:

![Screenshot](https://user-images.githubusercontent.com/874370/75470466-052a2700-5991-11ea-8e9a-46445b17e5df.png)

The classes are exported here (lines 19–20):

https://github.com/DevExpress/testcafe-hammerhead/blob/ad39cfb2487f1e7c92a02b377fb6e6f305f91fe7/src/index.ts#L13-L27

but have no type definitions here:

https://github.com/DevExpress/testcafe-hammerhead/blob/ad39cfb2487f1e7c92a02b377fb6e6f305f91fe7/ts-defs/index.d.ts#L19-L46

We import these classes from `testcafe-hammerhead` to implement a delayed request hook, extending `RequestHook` from `testcafe`. Re-exporting them from `testcafe` would be even better, but either way we lack the types here.

**Comment by Farfurix** [comment]
@rbardini 

Hello,

Thank you for the detailed description. We will consider it in the context of the following issue: https://github.com/DevExpress/testcafe/issues/4819.

Since it is marked “HELP WANTED”, your PR is welcome.
