### ISSUE TITLE
Hammerhead proxy gets stuck on a particular site

### ISSUE THREAD

**Issue by Dmitry-Ostashev** [DevExpress/testcafe-hammerhead#2267]
See the source issue for details: https://github.com/DevExpress/testcafe-studio/issues/3019. 

How to reproduce:

1. Try to open the site from the bug report via testcafe-hammerhead, enter credentials and click the "Login" button.
2. The page will get into infinite loading.
3. Try to terminate testcafe-hammerhead by the Ctrl+C shortcut.
4. Nothing happens.

**Comment by miherlosev** [comment]
The tested website has a wrongly bundled CSS file. This CSS file contains about 400 thousand spaces.
The regular expressions inside of `StyleProcessor` hung due to [catastrophic backtracking](https://javascript.info/regexp-catastrophic-backtracking). The fix can be complex - optimize regular expressions, use CSS parsing instead of regular expressions or something else.
I replied to the customer about fixing the problematic CSS resource and customer promises to fix it - https://supportcenter.devexpress.com/internal/ticket/details/T868144#b5c71fdf-3b99-4f30-9ff1-6a1042825e91.

**Comment by Farfurix** [comment]
Fixed in https://github.com/DevExpress/testcafe-hammerhead/pull/2487
