### ISSUE TITLE
Can't delete an item

### ISSUE THREAD

**Issue by Sabou44** [DevExpress/testcafe-hammerhead#2293]
### What is your Scenario?

When I try to delete item confirmation window doesn't open. 

### What is the Current behavior?

![delete](https://user-images.githubusercontent.com/59806062/79330912-a1e15d80-7f1a-11ea-8bc7-7e1b5af22b2a.PNG)
 

### What is the Expected behavior?

![delete_confirm](https://user-images.githubusercontent.com/59806062/79330929-a73ea800-7f1a-11ea-8fb4-4c0af188be37.PNG)

 
### Steps to Reproduce:

1. Go to https://jazz.net/
2. Log-in or register
3. Got to https://jazz.net/preview02-ccm/web/projects/JKE%20Account%20Mgmt%20Program#action=com.ibm.team.apt.search&predef=all&tq=1586945976000
4. Select an item to delete
 
### Your Environment details:

* testcafe version: v1.2.3
* node.js version: v10.16.3
* browser name and version: Firefox 75.0 and Chrome 81.0.4044.92
* platform and version: Windows 10 Pro

**Comment by LavrovArtem** [comment]
Hello,

The confirmation window should not open when you run the test because it will freeze automation. TestCafe allows you to handle native browser dialogs whenever they are invoked during the test run. For more details see: [Handling Native Dialogs](https://devexpress.github.io/testcafe/documentation/test-api/handling-native-dialogs.html)

**Comment by Sabou44** [comment]
Hello,

Thank you very much for that quick response.
Indeed my problem has been solved by calling the [setNativeDialogHandler(...)](https://devexpress.github.io/testcafe/documentation/test-api/handling-native-dialogs.html) function.

**Comment by LavrovArtem** [comment]
You are welcome!
