### ISSUE TITLE
`getProxyUrl` doesn't resolve relative paths for special page URLs

### ISSUE THREAD

**Issue by benmonro** [DevExpress/testcafe-hammerhead#2399]
### What is your Test Scenario?
when using the clientScripts in a testcafe config, if you then try to use `t.navigateTo` an error occurs.  all details and repro steps can be found here: https://github.com/testing-library/testcafe-testing-library/issues/222
 
### What is the Current behavior?

 error
### What is the Expected behavior?

 no error
### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by miherlosev** [comment]
Steps to reproduce:
 * `git clone https://github.com/SamuelDavis/testing-library-testcafe-integration;`
* `cd testing-library-testcafe-integration;`
* `npm install;`
* `npx testcafe chrome tests.js;`

**Comment by AndreyBelym** [comment]
I would say that `getFirstDestUrl` function works correctly in this case since [the error that we use to parse stack](https://github.com/DevExpress/testcafe-hammerhead/blob/6dfd1442bc290746e19ac77ff42fdadb095bbcbc/src/processing/script/transform.ts#L124) is originated from the service TestCafe script - the injected client script, not by some page script, and doesn't contain any proxied URL:

```
Error
    at beforeTransform (http://172.22.14.234:59840/hammerhead.js:28337:19)
    at transformProgram (http://172.22.14.234:59840/hammerhead.js:28409:9)
    at processScript (http://172.22.14.234:59840/hammerhead.js:27817:46)
    at FunctionWrapper (http://172.22.14.234:59840/hammerhead.js:19904:121)
    at http://172.22.14.234:59840/custom-client-scripts/__node_modules_@testing-library_dom_dist_@testing-library_dom_umd_js:14115:7
    at createCommonjsModule (http://172.22.14.234:59840/custom-client-scripts/__node_modules_@testing-library_dom_dist_@testing-library_dom_umd_js:129:7)
    at http://172.22.14.234:59840/custom-client-scripts/__node_modules_@testing-library_dom_dist_@testing-library_dom_umd_js:13420:19
    at http://172.22.14.234:59840/custom-client-scripts/__node_modules_@testing-library_dom_dist_@testing-library_dom_umd_js:5:29
    at http://172.22.14.234:59840/custom-client-scripts/__node_modules_@testing-library_dom_dist_@testing-library_dom_umd_js:6:2"
```

I think that `getProxyUrl` is the real culprit here. It returns incorrect results when handling relative URLs called on the proxied `about:blank` page. Compare this:

![image](https://user-images.githubusercontent.com/4479386/89437865-c4f57e80-d750-11ea-96bc-90203a597c34.png)
![image](https://user-images.githubusercontent.com/4479386/89437932-d9d21200-d750-11ea-9c8d-df5e8280f50d.png)

**Comment by miherlosev** [comment]
@AndreyBelym is right.

In case, if the stack doesn't contain the tested page URL, we are trying to calculate it using the `getProxyUrl('./')` function [call](https://github.com/DevExpress/testcafe-hammerhead/blob/6dfd1442bc290746e19ac77ff42fdadb095bbcbc/src/processing/script/transform.ts#L129).
