### ISSUE TITLE
Vulnerability found in dependency 'lodash'

### ISSUE THREAD

**Issue by michalmos** [DevExpress/testcafe-hammerhead#2509]
Testcafe-hammerhead version: `17.1.20`

After running the vulnerability scanner `Retire.js`, you can find a vulnerability in dependency `lodash`.

The full report:
`lodash 4.17.19 has known vulnerabilities: severity: low; summary: Prototype pollution attack; https://snyk.io/vuln/SNYK-JS-LODASH-590103`

Please update the dependency version to 4.17.20.

**Comment by Farfurix** [comment]
@michalmos 

Hello,

Our current `testcafe@1.10.0` version includes `lodash@4.17.20` after installing due to [semver](https://docs.npmjs.com/cli/v6/using-npm/semver). We have the [caret range](https://docs.npmjs.com/cli/v6/using-npm/semver#caret-ranges-123-025-004) for this package in `testcafe-hammerhead`: `"lodash": "^4.17.19"`. You mentioned `testcafe-hammerhead@17.1.20` in the description, so I suppose you're using `testcafe@1.9.4`. I suggest you update your TestCafe version to `v1.10.0` or [update](https://docs.npmjs.com/cli/v6/commands/npm-update#description) your current `lodash` dependencies:
```
npm --depth 9999 update lodash
```

**Comment by michalmos** [comment]
Hey, I see that `testcafe@1.10.1` still has the `lodash` vulnerability.
Can you verify this please? @Farfurix

**Comment by Farfurix** [comment]
@michalmos 

Hello,

The `npm i` command will install lodash@4.17.20 due to semver. You can track the `lodash` update here: https://github.com/DevExpress/testcafe-hammerhead/pull/2543.
