### ISSUE TITLE
Images not Displaying on https://www.nvidia.com/de-de/geforce-now/

### ISSUE THREAD

**Issue by SurfSkip** [DevExpress/testcafe-hammerhead#2972]
### What is your Scenario?

Images on the web page https://www.nvidia.com/de-de/geforce-now/ are not displaying when using testcafe-hammerhead.

### What is the Current behavior?

When visiting the web page using testcafe-hammerhead, images are not displayed as expected. Instead, they appear to be missing or not loading properly.

![image](https://github.com/DevExpress/testcafe-hammerhead/assets/140002481/bfe0c66f-ddfa-49ac-a2c5-3f76024d2568)

### What is the Expected behavior?

The expected behavior is that when accessing https://www.nvidia.com/de-de/geforce-now/ with testcafe-hammerhead, the images on the web page should load and display correctly. 

### What is your public website URL? (or attach your complete example)

https://surfskip.com/app 

### What is your TestCafe test code?

Latest TestCafe Hammerhead

### Steps to Reproduce

1.Open a terminal.
2.Run node node_modules/gulp/bin/gulp http-playground
3. Visit https://www.nvidia.com/de-de/geforce-now/

### TestCafe version

3.0.1

### Command-line arguments

Not sure what this means

**Comment by Bayheck** [comment]
Hello @SurfSkip
Thank you for sharing the example. We were able to reproduce the issue when running the test in the Hammerhead playground. However, we couldn't replicate the problem when running the test in TestCafe. This is because TestCafe of v3.0 and later uses the Native Automation mode in Chromium-based browsers ([https://testcafe.io/documentation/404237/guides/intermediate-guides/native-automation-mode](https://testcafe.io/documentation/404237/guides/intermediate-guides/native-automation-mode)).
Supporting this mode is one of our priorities, so please clarify why you don't want to use TestCafe in Native Automation mode.
