### ISSUE TITLE
Implement basic XHTML support

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#350]
![1](https://cloud.githubusercontent.com/assets/4133518/12230660/f6a1aeb6-b862-11e5-9f75-3efbe20caecc.png)

Presumably, problem grows from non closed our `meta` tag (`<meta xmlns="http://www.w3.org/1999/xhtml" class="charset-hammerhead-shadow-ui" charset="iso-8859-1">`).

**Comment by inikulin** [comment]
This is issue is caused by the fact that page has `XHTML`

**Comment by miherlosev** [comment]
I'm working on this

**Comment by miherlosev** [comment]
To fix bug we need to change our `meta` tags (`X-UA-Compatible` and `charset`) to selfclosed.

**Comment by inikulin** [comment]
@miherlosev Just thought it will not work if we will do it just for our tags. Since we serialize entire page we break it anyway serializing incorrectly user's `<meta>` tags. For now we can use the following solution:
1. Determine if page is an XML page (by analyzing doctype's publidId, details here: https://html.spec.whatwg.org/multipage/xhtml.html#parsing-xhtml-documents)
2. Use https://www.npmjs.com/package/sax for parsing and build XML-tree using it (like jsdom does:  https://github.com/tmpvar/jsdom/blob/master/lib/jsdom/browser/htmltodom.js#L106 but with the proper XML entities, like ProcessingInstruction and stuff).
3. Implement a XML serializer (using https://github.com/jindw/xmldom/blob/master/dom.js#L913 as starting point).
4. Implement PageProcessor adapter for XML tree

2 and 3 can be refactored to the separate package.

**Comment by husolukas** [comment]
is this issue solved? i have version 0.20.4 but i need to perform test on xhtml page

**Comment by willscripted** [comment]
> is this issue solved?

This appears to still be an issue. 

Anyone have a workaround? Is there a way to bypass hammerhead for urls, similar to the `bypass-proxy` setting?

We are seeing valid xml read in by hammerhead and returned invalid.

```
.
.
  <link [...] /><link [...] /><link [...] />
.
.
```
to
```
.
.
  <link [...]><link [...]><link [...]>
```
Notice that the tags are no longer closed after hammerhead processing.

**Comment by Farfurix** [comment]
@willscripted 

Hello,

We have plans to fix this issue, but I cannot provide you with any estimates on when it will be done.

**Comment by rhymiz** [comment]
hey @Farfurix , hopefully this doesn't come across as annoying,  but, checking in to see if this issue has at least been prioritized in your backlog? we don't always have the ability to replace `XHTML` with `HTML` tags, for _reasons_, so this feature would be a life saver.

**Comment by Farfurix** [comment]
@rhymiz 

Hello,

I'm afraid there are no estimates on this at the moment. We will update this thread once we have any result.

**Comment by rhymiz** [comment]
@Farfurix 

well, that's disappointing. nothing to do about it, I guess. looking forward to the update.
