### ISSUE TITLE
Click on a link on google.com redirects to non-proxied page via playground in IE only

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe-hammerhead#838]
[screencast](http://screencast.com/t/6Z92CYsj)

**Comment by inikulin** [comment]
Oh, that's bad. Guys, please, take care of it ASAP

**Comment by miherlosev** [comment]
I'm working on this

**Comment by miherlosev** [comment]
Redirect to target page is performed on client side using the following script:
### IE11
```js
 <script> window.googleJavaScriptRedirect = 1 </script>  
 <body style = "display: none">  
    <a href = "https://news.google.com/" id = link target = _parent>  
    <textarea id = "frm"></textarea>  
 </body>  
 <script > var n = {
	navigateTo : function (b, a, d) {
                                ...
				a.document.getElementById("link").click()
                                ...
         }
};
n.navigateTo(window.parent, window, "https://news.google.com/");
</script>  
....
```
After processing we don't proxy url for `#link `.
Supposedly, problem occurs because tag `a` is not closed or page hasn't surround `html` tag.
	
I am investigating it more deeply.

In google chrome used another script that is processed correctly.

**Comment by miherlosev** [comment]
Need to add an additional condition to the ElementSandbox.processElement
